### ISSUE TITLE
SkyDemo.apk crash in keyboard code

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#148]
Seen 1 report of this crash.  It may just be someone attempting to make their own Sky demo.

@abarth 

org.chromium.mojo.bindings.SerializationException: Trying to encode a null pointer for a non-nullable type.
at org.chromium.mojo.bindings.Encoder.encodeNullPointer(Encoder.java:453)
at org.chromium.mojo.bindings.Encoder.encode(Encoder.java:226)
at org.chromium.mojom.keyboard.CorrectionData.encode(CorrectionData.java:55)
at org.chromium.mojo.bindings.Encoder.encode(Encoder.java:218)
at org.chromium.mojom.keyboard.KeyboardClient_Internal$KeyboardClientCommitCorrectionParams.encode(KeyboardClient_Internal.java:300)
at org.chromium.mojo.bindings.Struct.serializeWithHeader(Struct.java:121)
at org.chromium.mojom.keyboard.KeyboardClient_Internal$Proxy.commitCorrection(KeyboardClient_Internal.java:65)
at org.domokit.keyboard.InputConnectionAdaptor.commitCorrection(InputConnectionAdaptor.java:43)
at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:331)
at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by ppiet** [comment]
Should this be moved to sky_engine or is it obsolete now?
