### ISSUE TITLE
We should catch exceptions from the okhttp library

### ISSUE THREAD

**Issue by Hixie** [domokit/mojo#184]
Right now they crash all of Sky.

e.g.:
```
E/AndroidRuntime( 3284): FATAL EXCEPTION: OkHttp Dispatcher
E/AndroidRuntime( 3284): Process: org.domokit.sky.demo, PID: 3284
E/AndroidRuntime( 3284): java.lang.RuntimeException: Malformed URL: 
E/AndroidRuntime( 3284): 	at com.squareup.okhttp.Request.url(Request.java:57)
E/AndroidRuntime( 3284): 	at com.squareup.okhttp.internal.http.HttpEngine.networkRequest(HttpEngine.java:584)
E/AndroidRuntime( 3284): 	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:212)
E/AndroidRuntime( 3284): 	at com.squareup.okhttp.Call.getResponse(Call.java:262)
E/AndroidRuntime( 3284): 	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:219)
E/AndroidRuntime( 3284): 	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:192)
E/AndroidRuntime( 3284): 	at com.squareup.okhttp.Call.access$100(Call.java:34)
E/AndroidRuntime( 3284): 	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:156)
E/AndroidRuntime( 3284): 	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
E/AndroidRuntime( 3284): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 3284): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 3284): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime( 3284): Caused by: java.net.MalformedURLException: Protocol not found: 
E/AndroidRuntime( 3284): 	at java.net.URL.<init>(URL.java:176)
E/AndroidRuntime( 3284): 	at java.net.URL.<init>(URL.java:125)
E/AndroidRuntime( 3284): 	at com.squareup.okhttp.Request.url(Request.java:55)
E/AndroidRuntime( 3284): 	... 11 more
```

**Comment by eseidelGoogle** [comment]
Specifically ian hit this when he replaced the baseURI passed to Url() in fetch.dart with "":
  String url = new sky.URL(relativeUrl, "").href;

**Comment by Hixie** [comment]
@abarth if the base URL is the empty string, you'll hit this when using fetch.

**Comment by collinjackson** [comment]
I ran into this crash with the image loader as well

**Comment by abarth** [comment]
@eseidelGoogle Fixed a number of these.  Please file a new issue if you see this happen again.
