### ISSUE TITLE
"mojo:dart_apptests_dartzip" test fails

### ISSUE THREAD

**Issue by smklein** [domokit/mojo#384]
From cloning the mojo repo, building, and running ```mojo/tools/mojob.py test```, I see a failure from the "mojo:dart_apptests_dartzip" test.

The actual subtest being run is ```out/Debug/mojo_shell --map-origin=https://core.mojoapps.io/=http://127.0.0.1:42328/ mojo:dart_apptests_dartzip```

This causes the "App tests" to fail. Dart seems to be unhappy with a local IPv6 address, as indicated by ```Invalid argument(s): Invalid internet address 0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:1```.

It seems that the ["Lookup ANY" test] (https://github.com/domokit/mojo/blob/master/services/dart/dart_apptests/lib/src/io_internet_address_apptests.dart#L36) ends up calling the following:

[InternetAddress.lookup('localhost', type:InternetAddressType.ANY)](https://github.com/domokit/mojo/blob/master/services/dart/dart_apptests/lib/src/io_internet_address_apptests.dart#L38), which calls
[_MojoInternetAddress._lookup(host, type)](https://github.com/domokit/mojo/blob/de23c489de78b97e161cfbd3325d4bc1da0b5769/mojo/dart/embedder/io/internet_address_patch.dart#L32), which is defined [here](https://github.com/domokit/mojo/blob/de23c489de78b97e161cfbd3325d4bc1da0b5769/mojo/dart/embedder/io/internet_address_patch.dart#L199).

This _lookup function determines that the address family of type "ANY" is equal to zero.
Once the call to [var response = await hostResolver.ptr.getHostAddresses(host, family)](https://github.com/domokit/mojo/blob/master/mojo/dart/embedder/io/internet_address_patch.dart#L202) is made from _lookup, the response contains the following:

- Response: HostResolverGetHostAddressesResponseParams(
  - result: NetworkError(code: 0, description: net::OK),
  - addresses: [
  - NetAddress(
    * family: 2,
    * ipv4: null,
    * ipv6: NetAddressIPv6(port: 0, addr: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])),
  - NetAddress(
    * family: 1,
    * ipv4: NetAddressIPv4(port: 0, addr: [127, 0, 0, 1]),
    * ipv6: null)])

Here, we see an IPv6 address, which should be "0:0:0:0:0:0:0:1", defined as "0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:1". This causes issues later, when parsing the IP address. I think this is a bug in the getHostAddresses function, but I can only trace that back to [this](https://github.com/domokit/mojo/blob/master/mojo/services/network/public/interfaces/host_resolver.mojom#L13) mojom file.

Relevant test output:

```
Running mojo:dart_apptests_dartzip.... Failed test: "mojo_shell '--map-origin=https://core.mojoapps.io/=http://127.0.0.1:45384/' 'mojo:dart_apptests_dartzip'"
  due to shell exit code 1
------------------------------------------------------------------------
Observatory listening on http://127.0.0.1:33866
00:00 +0: dart_apptests Connection
00:00 +1: dart_apptests Echo Service Apptests String
00:00 +2: dart_apptests Echo Service Apptests Empty String
00:00 +3: dart_apptests Echo Service Apptests Null String
00:00 +4: dart_apptests Echo Service Apptests Delayed Success
00:00 +5: dart_apptests Echo Service Apptests Delayed Close
00:00 +6: dart_apptests InternetAddress Apptests Parse IPv4
00:00 +7: dart_apptests InternetAddress Apptests Parse IPv6
00:00 +8: dart_apptests InternetAddress Apptests Reverse
00:00 +9: dart_apptests InternetAddress Apptests Lookup IPv4
00:00 +10: dart_apptests InternetAddress Apptests Lookup ANY
00:00 +10 -1: dart_apptests InternetAddress Apptests Lookup ANY
  Invalid argument(s): Invalid internet address 0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:1
  dart:io                                                           _MojoInternetAddress._lookup.<async>
  ../packages/stack_trace/src/stack_zone_specification.dart 134:26  StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
  ../packages/stack_trace/src/stack_zone_specification.dart 205:15  StackZoneSpecification._run
  ../packages/stack_trace/src/stack_zone_specification.dart 134:14  StackZoneSpecification.registerUnaryCallback.<fn>
  dart:async                                                        _Future._asyncComplete.<fn>
  ../packages/stack_trace/src/stack_zone_specification.dart 205:15  StackZoneSpecification._run
  ../packages/stack_trace/src/stack_zone_specification.dart 124:48  StackZoneSpecification.registerCallback.<fn>
  ===== asynchronous gap ===========================
  dart:io                                                           _MojoInternetAddress._lookup.<async>
  ../packages/stack_trace/src/stack_zone_specification.dart 134:26  StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
  ../packages/stack_trace/src/stack_zone_specification.dart 205:15  StackZoneSpecification._run
  ../packages/stack_trace/src/stack_zone_specification.dart 134:14  StackZoneSpecification.registerUnaryCallback.<fn>
  dart:async                                                        _Future._asyncComplete.<fn>
  ../packages/stack_trace/src/stack_zone_specification.dart 205:15  StackZoneSpecification._run
  ../packages/stack_trace/src/stack_zone_specification.dart 124:48  StackZoneSpecification.registerCallback.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                        Future.Future.microtask.<fn>
  ../packages/stack_trace/src/stack_zone_specification.dart 205:15  StackZoneSpecification._run
  ../packages/stack_trace/src/stack_zone_specification.dart 124:48  StackZoneSpecification.registerCallback.<fn>
  dart:async                                                        _CustomZone.bindCallback.<fn>
  ../packages/stack_trace/src/stack_zone_specification.dart 205:15  StackZoneSpecification._run
  ../packages/stack_trace/src/stack_zone_specification.dart 124:48  StackZoneSpecification.registerCallback.<fn>
  ===== asynchronous gap ===========================
  dart:io                                                           InternetAddress.lookup
  src/io_internet_address_apptests.dart 38:33                       tests.<fn>.<fn>.<async>
  dart:async                                                        Future.Future.microtask.<fn>
  ../packages/stack_trace/src/stack_zone_specification.dart 205:15  StackZoneSpecification._run
  ../packages/stack_trace/src/stack_zone_specification.dart 124:48  StackZoneSpecification.registerCallback.<fn>
  dart:async                                                        _CustomZone.bindCallback.<fn>
  ../packages/stack_trace/src/stack_zone_specification.dart 205:15  StackZoneSpecification._run
  ../packages/stack_trace/src/stack_zone_specification.dart 124:48  StackZoneSpecification.registerCallback.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                        Future.Future.microtask
  src/io_internet_address_apptests.dart                             tests.<fn>.<fn>
  ../packages/test/src/backend/declarer.dart 48:47                  Declarer.test.<fn>.<fn>
  ../packages/stack_trace/src/stack_zone_specification.dart 134:26  StackZoneSpecification.registerUnaryCallback.<fn>.<fn>
  ../packages/stack_trace/src/stack_zone_specification.dart 205:15  StackZoneSpecification._run
  ../packages/stack_trace/src/stack_zone_specification.dart 134:14  StackZoneSpecification.registerUnaryCallback.<fn>
  dart:async                                                        _Future._asyncComplete.<fn>
  ../packages/stack_trace/src/stack_zone_specification.dart 205:15  StackZoneSpecification._run
  ../packages/stack_trace/src/stack_zone_specification.dart 124:48  StackZoneSpecification.registerCallback.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                        _Future.then
  ../packages/test/src/backend/declarer.dart 48:31                  Declarer.test.<fn>
  dart:async                                                        Future.Future.<fn>
  ../packages/stack_trace/src/stack_zone_specification.dart 205:15  StackZoneSpecification._run
  ../packages/stack_trace/src/stack_zone_specification.dart 124:48  StackZoneSpecification.registerCallback.<fn>
  dart:async                                                        _CustomZone.bindCallback.<fn>
  ../packages/stack_trace/src/stack_zone_specification.dart 205:15  StackZoneSpecification._run
  ../packages/stack_trace/src/stack_zone_specification.dart 124:48  StackZoneSpecification.registerCallback.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                        Future.Future
  ../packages/test/src/backend/invoker.dart 225:13                  Invoker._onRun.<fn>.<fn>
  dart:async                                                        runZoned
  ../packages/test/src/utils.dart 160:12                            runZonedWithValues.<fn>
  dart:async                                                        runZoned
  ../packages/test/src/utils.dart 159:10                            runZonedWithValues
  ../packages/test/src/backend/invoker.dart 216:7                   Invoker._onRun.<fn>
  ../packages/stack_trace/src/chain.dart 75:24                      Chain.capture.<fn>
  dart:async                                                        runZoned
  ../packages/stack_trace/src/chain.dart 73:12                      Chain.capture
  ../packages/test/src/backend/invoker.dart 215:11                  Invoker._onRun
  ../packages/test/src/backend/live_test_controller.dart 167:11     LiveTestController._run
  ../packages/test/src/backend/live_test_controller.dart 38:31      _LiveTest.run
  
00:00 +10 -1: dart_apptests InternetAddress Apptests Lookup failure
00:00 +11 -1: dart_apptests Http Apptests Http Server Bind
00:00 +12 -1: dart_apptests Http Apptests Http Server Request 404
00:01 +13 -1: dart_apptests Http Apptests Http Server Response
00:01 +14 -1: dart_apptests Ping-Pong Service Apptests Ping Service To Pong Client
00:01 +15 -1: dart_apptests Ping-Pong Service Apptests Ping Target URL
00:01 +16 -1: dart_apptests Ping-Pong Service Apptests Ping Target Service
00:01 +17 -1: dart_apptests Ping-Pong Service Apptests Get Target Service
00:01 +18 -1: dart_apptests Versioning Apptests Struct
00:01 +19 -1: dart_apptests Versioning Apptests QueryVersion
00:01 +20 -1: dart_apptests Versioning Apptests RequireVersion
00:01 +21 -1: dart_apptests Versioning Apptests CallNonexistentMethod
ERROR: validation_errors.cc(61): Invalid message: VALIDATION_ERROR_MESSAGE_HEADER_UNKNOWN_METHOD
00:01 +22 -1: TERMINATE SHELL CONNECTION
00:01 +23 -1: Some tests failed.

[0816/150600:ERROR:dart_error.cc(19)] Unhandled exception:
Uncaught Error: Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
[0816/150600:ERROR:dart_error.cc(28)] #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

../../mojo/dart/embedder/dart_controller.cc:248: error handle: 'result':
    'Unhandled exception:
Uncaught Error: Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)'
Received signal 6
#0 0x7faf4df5c51e base::debug::StackTrace::StackTrace()
#1 0x7faf4df5c05f base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7faf52b3c340 <unknown>
#3 0x7faf5279dcc9 gsignal
#4 0x7faf527a10d8 abort
#5 0x7faf4e6a6ab6 dart::OS::Abort()
#6 0x7faf4de76e97 mojo::dart::RunIsolate()
#7 0x7faf4de7711d mojo::dart::DartController::RunDartScript()
#8 0x7faf4dcecff6 dart::DartApp::OnAppLoaded()
#9 0x7faf4dceea29 base::internal::RunnableAdapter<>::Run()
#10 0x7faf4dcee96c _ZN4base8internal12InvokeHelperILb0EvNS0_15RunnableAdapterIMN4dart7DartAppEFvvEEENS0_8TypeListIJPS4_EEEE8MakeItSoES7_S9_
#11 0x7faf4dcee938 _ZN4base8internal7InvokerINS_13IndexSequenceIJLm0EEEENS0_9BindStateINS0_15RunnableAdapterIMN4dart7DartAppEFvvEEEFvPS7_ENS0_8TypeListIJNS0_17UnretainedWrapperIS7_EEEEEEENSD_IJNS0_12UnwrapTraitsISF_EEEEENS0_12InvokeHelperILb0EvSA_NSD_IJSB_EEEEEFvvEE3RunEPNS0_13BindStateBaseE
#12 0x7faf4dce6c1e base::Callback<>::Run()
#13 0x7faf4df609b8 base::debug::TaskAnnotator::RunTask()
#14 0x7faf4dd5c8e1 base::MessageLoop::RunTask()
#15 0x7faf4dd5ca38 base::MessageLoop::DeferOrRunPendingTask()
#16 0x7faf4dd5cc02 base::MessageLoop::DoWork()
#17 0x7faf4de94fa4 mojo::common::MessagePumpMojo::DoRunLoop()
#18 0x7faf4de94ecf mojo::common::MessagePumpMojo::Run()
#19 0x7faf4dd5c49f base::MessageLoop::RunHandler()
#20 0x7faf4dd9ebf4 base::RunLoop::Run()
#21 0x7faf4dd5ba16 base::MessageLoop::Run()
#22 0x7faf4de6ce71 mojo::ContentHandlerFactory::ManagedDelegate::RunApplication()
#23 0x7faf4de7006c mojo::(anonymous namespace)::ApplicationThread::ThreadMain()
#24 0x7faf4de05059 base::(anonymous namespace)::ThreadFunc()
#25 0x7faf52b34182 start_thread
#26 0x7faf5286147d clone
  r8: 00007faf4ce9a700  r9: 6f73693a74726164 r10: 0000000000000008 r11: 0000000000000202
 r12: 0000000000000000 r13: 0000000000000000 r14: 00007faf4ce9a9c0 r15: 00007faf4ce9a700
  di: 00000000000064f8  si: 0000000000006503  bp: 00007faf4ce989b0  bx: 00007faf4ce9a700
  dx: 0000000000000006  ax: 0000000000000000  cx: ffffffffffffffff  sp: 00007faf4ce98798
  ip: 00007faf5279dcc9 efl: 0000000000000202 cgf: 0000000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000

------------------------------------------------------------------------
Failed
```

**Comment by smklein** [comment]
@johnmccutchan, I'm very new to both mojo and Dart -- do you know why this test is failing?

**Comment by johnmccutchan** [comment]
Hi,

I can't reproduce. How did you generate the following command line:

$ out/Debug/mojo_shell --map-origin=https://core.mojoapps.io/=http://127.0.0.1:42328/ mojo:dart_apptests_dartzip

?

FWIW-

$ ./mojo/tools/mojob.py test

Works.

$ ./out/Debug/mojo_shell mojo:dart_apptests_dartzip

Works.

**Comment by smklein** [comment]
Hrm... running

`$ ./mojo/tools/mojob.py test`

Causes this test to fail -- this results in the output:
```
Running mojo:dart_apptests_dartzip.... Failed test: "mojo_shell '--map-origin=https://core.mojoapps.io/=http://127.0.0.1:54699/' 'mojo:dart_apptests_dartzip'"
  due to shell exit code 1
```

(which is where I got the command from).

Running this:
`$ ./out/Debug/mojo_shell mojo:dart_apptests_dartzip`
Also causes the same "Invalid internet address 0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:1" failure.

I've just cloned and built the repo from github on goobuntu -- is there some IP setup I may have missed?

**Comment by johnmccutchan** [comment]
Hi,

I'm not sure. Note that the build bots also do not have an issue with this test:

http://build.chromium.org/p/client.mojo/console

John

**Comment by jamesr** [comment]
The buildbots are failing with exactly this error now.  They were recently upgraded from Precise to Trusty, if that's related:

http://build.chromium.org/p/client.mojo/builders/Mojo%20Linux/builds/3776/steps/App%20tests/logs/stdio

I can't repro locally.  It looks like the string value is not making it through correctly.

@smklein - can you still repro?

**Comment by jamesr** [comment]
Looks like the bug is when an ANY lookup results in an IPv6 address the resulting address is stringified incorrectly.  My box gives ipv4 for ANY lookups but others are probably configured differently.

**Comment by jamesr** [comment]
@viettrungluu-cr  points out the 16 here https://github.com/domokit/mojo/blob/master/mojo/dart/embedder/io/mojo_patch.dart#L94 is probably the culprit.

**Comment by smklein** [comment]
Just to confirm, I am still seeing this issue locally.
Running ubuntu 14.04 LTS trusty, kernel 3.13.0-61-generic.
Same steps as I mentioned earlier to repro.

**Comment by smklein** [comment]
So this is obviously a total hack, but by changing
https://github.com/domokit/mojo/blob/master/mojo/dart/embedder/io/mojo_patch.dart#L96
from 
```var divider = (i != 15) ? ':' : '';```
(produces 0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:1)
to
```var divider = (i != 15 && i % 2 != 0) ? ':' : '';```
(produces 00:00:00:00:00:00:00:01)
The test no longer fails.

This confirms the failure is from misreading an IPv6 address.
I believe that the expected format for IPv6 addresses is 8 sets of 4 hexadecimal digits (i.e., xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx).

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/1309313002/

**Comment by johnmccutchan** [comment]
Code for printing the IPv6 addresses was obviously broken.
