### ISSUE TITLE
Mojom: Arrays of interfaces not supported

### ISSUE THREAD

**Issue by viettrungluu-cr** [domokit/mojo#412]
I wanted/needed to use arrays of interfaces, and got:

```
Traceback (most recent call last):
  File "../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 221, in <module>
    sys.exit(main())
  File "../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 215, in main
    processor.ProcessFile(args, remaining_args, generator_modules, filename)
  File "../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 106, in ProcessFile
    filename)
  File "../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 145, in _GenerateModule
    generator.GenerateFiles(filtered_args)
  File "/home/vtl/projects/mojo/src/mojo/public/tools/bindings/generators/mojom_cpp_generator.py", line 416, in GenerateFiles
    self.Write(self.GenerateModuleHeader(),
  File "/home/vtl/projects/mojo/src/mojo/public/tools/bindings/pylib/mojom/generate/template_expander.py", line 56, in GeneratorInternal
    **kwargs)
  File "/home/vtl/projects/mojo/src/mojo/public/tools/bindings/pylib/mojom/generate/template_expander.py", line 46, in ApplyTemplate
    return template.render(params)
  File "/home/vtl/projects/mojo/src/mojo/public/third_party/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/vtl/projects/mojo/src/mojo/public/third_party/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vtl/projects/mojo/src/mojo/public/tools/bindings/generators/cpp_templates/module.h.tmpl", line 78, in top-level template code
    {%    include "interface_declaration.tmpl" %}
  File "/home/vtl/projects/mojo/src/mojo/public/tools/bindings/generators/cpp_templates/interface_declaration.tmpl", line 47, in top-level template code
    virtual void {{method.name}}({{interface_macros.declare_request_params("", method)}}) = 0;
  File "/home/vtl/projects/mojo/src/mojo/public/tools/bindings/generators/cpp_templates/interface_macros.tmpl", line 18, in template
    {{declare_params(prefix, method.parameters)}}
  File "/home/vtl/projects/mojo/src/mojo/public/tools/bindings/generators/cpp_templates/interface_macros.tmpl", line 3, in template
    {{param.kind|cpp_const_wrapper_type}} {{prefix}}{{param.name}}
  File "/home/vtl/projects/mojo/src/mojo/public/tools/bindings/generators/mojom_cpp_generator.py", line 189, in GetCppConstWrapperType
    return "mojo::Array<%s>" % GetCppArrayArgWrapperType(kind.kind)
  File "/home/vtl/projects/mojo/src/mojo/public/tools/bindings/generators/mojom_cpp_generator.py", line 106, in GetCppArrayArgWrapperType
    raise Exception("Arrays of interfaces not yet supported!")
Exception: Arrays of interfaces not yet supported!
```

So the C++ bindings don't support them. Don't know about other bindings.

/cc @vardhan-cr @AlexandreZani @MitchRudominer @yzshen

**Comment by MitchRudominer** [comment]
OK, I will take this. Trung please let me know how urgent this is for you as I will  interleave it with my work on the parser/compiler.

**Comment by viettrungluu-cr** [comment]
Not very urgent, since I can work around it in a way that's good enough for
now. Thanks.

**Comment by MitchRudominer** [comment]
Assigning to vardhan since he is taking over https://codereview.chromium.org/1393633002/.
