### ISSUE TITLE
Segmentation fault in Dart VM

### ISSUE THREAD

**Issue by emembrives** [domokit/mojo#453]
Here is the stack trace:
```
#0  0x9f682962 in CompareAndSwapWord (new_value=2818574, old_value=2818570, ptr=0xa17408f8)
    at ../../dart/runtime/vm/atomic_android.h:33
#1  UpdateTagBit<dart::RawObject::CanonicalObjectTag> (value=true, 
    this=<error reading variable: Cannot access memory at address 0x9fc13c2c>)
    at ../../dart/runtime/vm/raw_object.h:515
#2  SetCanonical (this=<error reading variable: Cannot access memory at address 0x9fc13c2c>)
    at ../../dart/runtime/vm/raw_object.h:368
#3  SetCanonical (this=0x9fc13c28) at ../../dart/runtime/vm/object.h:259
#4  dart::Instance::CheckAndCanonicalize (this=<optimized out>, error_str=<optimized out>)
    at ../../dart/runtime/vm/object.cc:14456
#5  0x9f67b266 in dart::Array::CheckAndCanonicalizeFields (this=0xa1929590, error_str=0x9d7004d8)
    at ../../dart/runtime/vm/object.cc:20066
#6  0x9f682840 in dart::Instance::CheckAndCanonicalize (this=0xa1929590, error_str=<optimized out>)
    at ../../dart/runtime/vm/object.cc:14426
#7  0x9f6a27cc in dart::Parser::TryCanonicalize (this=this@entry=0x9d7007b0, instance=..., 
    token_pos=token_pos@entry=1568) at ../../dart/runtime/vm/parser.cc:11940
#8  0x9f6be820 in dart::Parser::ParseListLiteral (this=this@entry=0x9d7007b0, type_pos=<optimized out>, 
    is_const=<optimized out>, type_arguments=...) at ../../dart/runtime/vm/parser.cc:12665
#9  0x9f6bf880 in dart::Parser::ParseCompoundLiteral (this=this@entry=0x9d7007b0)
    at ../../dart/runtime/vm/parser.cc:12994
#10 0x9f6b1500 in dart::Parser::ParsePrimary (this=this@entry=0x9d7007b0)
    at ../../dart/runtime/vm/parser.cc:13835
#11 0x9f6b774a in dart::Parser::ParsePostfixExpr (this=this@entry=0x9d7007b0)
    at ../../dart/runtime/vm/parser.cc:11668
#12 0x9f6b79e2 in dart::Parser::ParseUnaryExpr (this=this@entry=0x9d7007b0)
    at ../../dart/runtime/vm/parser.cc:10977
#13 0x9f6b7d5a in dart::Parser::ParseBinaryExpr (this=this@entry=0x9d7007b0, min_preced=4)
    at ../../dart/runtime/vm/parser.cc:10372
#14 0x9f6b867a in dart::Parser::ParseConditionalExpr (this=this@entry=0x9d7007b0)
    at ../../dart/runtime/vm/parser.cc:10897
#15 0x9f6b83f6 in dart::Parser::ParseExpr (this=this@entry=0x9d7007b0, 
    consume_cascades=consume_cascades@entry=true, require_compiletime_const=false)
    at ../../dart/runtime/vm/parser.cc:10835
#16 0x9f6b99e8 in dart::Parser::ParseStaticFinalGetter (this=0x9d7007b0, func=...)
    at ../../dart/runtime/vm/parser.cc:1228
```

Ask in private if you need repro steps.

cc/ @johnmccutchan

**Comment by emembrives** [comment]
Duplicate of #192
