### ISSUE TITLE
Mojom Compiler error when using enums as Types.

### ISSUE THREAD

**Issue by gregsimon** [domokit/mojo#467]
This code used to work :-)
```
module audio;
...
enum AudioFormat {
  UNKNOWN = 1,
  PCM_8_11025Hz,
  PCM_16_11025Hz,
  PCM_16_22050Hz,
  PCM_16_44100Hz,
  PCM_16_48000Hz,
  LAST = PCM_16_48000Hz
};

struct AudioDevice {
  uint32 device_id;
  string name;
  Direction direction;
  uint32 num_channels;
  array<AudioFormat>? formats;
};
```
Now I get an error:

FAILED: python ../../mojo/public/tools/bindings/mojom_bindings_generator.py ../../sky/services/audio/audio.mojom --use_bundled_pylibs -d ../../ -I ../../ -I ../../ -o /usr/local/google/home/gregsimon/sky/src/out/android_Release/gen
Traceback (most recent call last):
  File "../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 221, in <module>
    sys.exit(main())
  File "../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 215, in main
    processor.ProcessFile(args, remaining_args, generator_modules, filename)
  File "../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 106, in ProcessFile
    filename)
  File "../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 145, in _GenerateModule
    generator.GenerateFiles(filtered_args)
  File "/usr/local/google/home/gregsimon/sky/src/mojo/public/tools/bindings/generators/mojom_dart_generator.py", line 446, in GenerateFiles
    lib_module = self.GenerateLibModule(args)
  File "/usr/local/google/home/gregsimon/sky/src/mojo/public/tools/bindings/pylib/mojom/generate/template_expander.py", line 56, in GeneratorInternal
    **kwargs)
  File "/usr/local/google/home/gregsimon/sky/src/mojo/public/tools/bindings/pylib/mojom/generate/template_expander.py", line 46, in ApplyTemplate
    return template.render(params)
  File "/usr/local/google/home/gregsimon/sky/src/mojo/public/third_party/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/google/home/gregsimon/sky/src/mojo/public/third_party/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/google/home/gregsimon/sky/src/mojo/public/tools/bindings/generators/dart_templates/module.lib.tmpl", line 16, in top-level template code
    {%- include "module_definition.tmpl" %}
  File "/usr/local/google/home/gregsimon/sky/src/mojo/public/tools/bindings/generators/dart_templates/module_definition.tmpl", line 15, in top-level template code
    {{ struct_def(struct) }}
  File "/usr/local/google/home/gregsimon/sky/src/mojo/public/tools/bindings/generators/dart_templates/struct_definition.tmpl", line 66, in template
    {{encoding_macros.decode('result.' ~ packed_field.field|name, packed_field.field.kind, 8+packed_field.offset, packed_field.bit)|indent(6)}}
  File "/usr/local/google/home/gregsimon/sky/src/mojo/public/tools/bindings/generators/dart_templates/encoding_macros.tmpl", line 99, in template
    {{variable}} = decoder{{level}}.{{kind|decode_method(offset, bit)}};
  File "/usr/local/google/home/gregsimon/sky/src/mojo/public/tools/bindings/generators/mojom_dart_generator.py", line 306, in DecodeMethod
    methodName = _DecodeMethodName(kind)
  File "/usr/local/google/home/gregsimon/sky/src/mojo/public/tools/bindings/generators/mojom_dart_generator.py", line 300, in _DecodeMethodName
    return _DecodeMethodName(kind.kind) + 'Array'
  File "/usr/local/google/home/gregsimon/sky/src/mojo/public/tools/bindings/generators/mojom_dart_generator.py", line 305, in _DecodeMethodName
    return _spec_to_decode_method[kind.spec]
KeyError: 'x:audio.AudioFormat'

**Comment by MitchRudominer** [comment]
I'm investigating.

**Comment by MitchRudominer** [comment]
I added github markdown markers around the code Greg pasted in so it renders correctly.

**Comment by AlexandreZani** [comment]
A few preliminary findings:

1) The bug appears to be limited to the dart bindings generators.
2) The bug appears to be limited to enums which were last modified by this CL: https://codereview.chromium.org/1351683003/

**Comment by MitchRudominer** [comment]
Alex says he has a fix. Assigning the bug to him.

**Comment by MitchRudominer** [comment]
I can confirm that syncing back to before the CL Alex mentions makes the problem go away.

**Comment by AlexandreZani** [comment]
Can you confirm and close Greg?
