### ISSUE TITLE
No static method 'MojoQueryAndReadMessage' declared in class 'MojoMessagePipeNatives'.

### ISSUE THREAD

**Issue by afandria** [domokit/mojo#481]
I was running my Flutter app on Android using mojo shell (`pub run sky_tools run_mojo`)

It looks like there is a Mojo Dart error as soon as I try to load any images.

```
[1020/181752:ERROR:dart_error.cc(16)] Unhandled exception:
No static method 'MojoQueryAndReadMessage' declared in class 'MojoMessagePipeNatives'.

NoSuchMethodError: method not found: 'MojoQueryAndReadMessage'
Receiver: Type: class 'MojoMessagePipeNatives'
Arguments: [103, 0, null, null, _List len:5]
#0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:188)
#1      MojoMessagePipeQueryAndReadState.queryAndRead (packages/mojo/src/message_pipe.dart:43)
#2      MojoMessagePipeEndpoint.queryAndRead (packages/mojo/src/message_pipe.dart:169)
#3      Proxy.handleRead (packages/mojo/src/proxy.dart:37)
#4      MojoEventStreamListener.listen.<anonymous closure> (packages/mojo/src/event_stream.dart:207)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1087)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#8      _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:744)
#9      _StreamController._add (dart:async/stream_controller.dart:616)
#10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1087)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#13     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:744)
#14     _StreamController._add (dart:async/stream_controller.dart:616)
#15     _StreamController.add (dart:async/stream_controller.dart:562)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)
```

**Comment by afandria** [comment]
It might be this; I'm going to check.

https://github.com/flutter/engine/commit/77622e13b629f422d99e9ad2962d24344f2595e1

**Comment by jamesr** [comment]
It is.  You need to pin to mojo 0.2.0 for now, sorry.

**Comment by jamesr** [comment]
@zanderso

**Comment by zanderso** [comment]
Should we close this, or leave it open until landing the change with the new procedure?
