### ISSUE TITLE
activity.setSystemUiVisibility throws exception in MojoShell

### ISSUE THREAD

**Issue by apwilson** [domokit/mojo#502]
```dart
[1030/124934:ERROR:dart_error.cc(16)] Unhandled exception:
'packages/mojo/src/application_connection.dart': Failed assertion: line 84: '!proxy.impl.isBound &&
        (remoteServiceProvider != null) &&
        remoteServiceProvider.impl.isBound' is not true.
#0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
#1      ApplicationConnection.requestService (packages/mojo/src/application_connection.dart:84)
#2      _Shell._connectToService (packages/flutter/src/services/shell.dart:59)
#3      _Shell.connectToService (packages/flutter/src/services/shell.dart:74)
#4      _initActivityProxy (packages/flutter/src/services/activity.dart:25)
#5      _activityProxy (packages/flutter/src/services/activity.dart:29)
#6      _activityProxy (packages/flutter/src/services/activity.dart:29)
#7      activity (packages/flutter/src/services/activity.dart:30)
#8      activity (packages/flutter/src/services/activity.dart:30)
```

**Comment by zanderso** [comment]
I believe this is the same issue as https://github.com/domokit/mojo/issues/496
