### ISSUE TITLE
New Mojom Parser: Constant values are constructed incorrectly in the Python translation layer

### ISSUE THREAD

**Issue by MitchRudominer** [domokit/mojo#519]
In mojom_translator.py in the function ConstFromMojom(), whose purpose is to translate a
mojom_types_mojom.DeclaredConstant to a module.Constant, I see:

const.value = self.EvalValue(mojom_const.value)

and examining the function EvalValue() I see that it returns an int, float, str or bool.

But this is not the correct data type for const.value. If you look at the function TranslateConstants() in mojom_dart_generator.py you can see that the constants value is supposed to be an instance of mojom.EnumValue, mojom.NamedValue, mojom.BuiltinValue, or a string representing a literal.

We had a similar problem with enum values and I (attempted to) fix it in
https://codereview.chromium.org/1425093005/diff/20001/mojo/public/tools/bindings/pylib/mojom/generate/mojom_translator.py.

Note that in mojom_types.mojom the value field of a DeclaredConstant is of type |Value| which  can be a |LiteralValue| a |UserValueReference| or a |BuiltInConstantValue|. So we need a Python function that translates a |Value| into a a mojom.EnumValue, mojom.NamedValue, mojom.BuiltinValue, or a string. If the |Value| is a |LiteralValue| it should be translated to a string. If the |Value| is a |BuiltinConstantValue| it should be translated to a mojom.BuiltinValue. If the |Value| is a |UserValueReference| then you look at the |value_key| to determine what the |UserValueReference| resolves to. It will resolve to either an EnumValue or another DeclaredConstant which will then map to a mojom.EnumValue or a mojom.NamedValue.

**Comment by MitchRudominer** [comment]
/cc @AlexandreZani 

For reference, here is the stack trace

```
[5/17] ACTION //mojo/public/interfaces/bindings:bindings__generator(//build/toolchain/linux:clang_x64)
Traceback (most recent call last):
  File "/home/rudominer/mojo/src/mojo/public/tools/bindings/run_code_generators.py", line 167, in <module>
    sys.exit(main())
  File "/home/rudominer/mojo/src/mojo/public/tools/bindings/run_code_generators.py", line 163, in main
    generator.GenerateFiles(filtered_args)
  File "/home/rudominer/mojo/src/mojo/public/tools/bindings/generators/mojom_dart_generator.py", line 450, in GenerateFiles
    lib_module = self.GenerateLibModule(args)
  File "/home/rudominer/mojo/src/mojo/public/tools/bindings/pylib/mojom/generate/template_expander.py", line 54, in GeneratorInternal
    parameters = generator(*args, **kwargs2)
  File "/home/rudominer/mojo/src/mojo/public/tools/bindings/generators/mojom_dart_generator.py", line 442, in GenerateLibModule
    return self.GetParameters(args)
  File "/home/rudominer/mojo/src/mojo/public/tools/bindings/generators/mojom_dart_generator.py", line 432, in GetParameters
    "module": resolver.ResolveConstants(self.module, ExpressionToText),
  File "/home/rudominer/mojo/src/mojo/public/tools/bindings/pylib/mojom/generate/constant_resolver.py", line 71, in ResolveConstants
    ResolveConstant(constant)
  File "/home/rudominer/mojo/src/mojo/public/tools/bindings/pylib/mojom/generate/constant_resolver.py", line 40, in ResolveConstant
    resolved_value = expression_to_text(constant.value)
  File "/home/rudominer/mojo/src/mojo/public/tools/bindings/generators/mojom_dart_generator.py", line 360, in ExpressionToText
    return TranslateConstants(token)
  File "/home/rudominer/mojo/src/mojo/public/tools/bindings/generators/mojom_dart_generator.py", line 352, in TranslateConstants
    if token[0] == '+':
TypeError: 'int' object has no attribute '__getitem__'
```
