### ISSUE TITLE
New Mojom Compiler: Missing gn deps

### ISSUE THREAD

**Issue by MitchRudominer** [domokit/mojo#528]
When I run mojob.py build with use_new_mojom_compiler = true in my args.gn I get the following error:

```
[128/6489] ACTION //mojo/services/gpu/interfaces:interfaces__generator(//build/toolchain/linux:clang_x86)
Traceback (most recent call last):
  File "/home/rudominer/mojo/src/mojo/public/tools/bindings/run_code_generators.py", line 62, in <module>
    from mojom.generate.generated import mojom_files_mojom
  File "/home/rudominer/mojo/src/mojo/public/tools/bindings/pylib/mojom/generate/generated/mojom_files_mojom.py", line 5, in <module>
    import mojo_bindings.descriptor as _descriptor
```

This problem may be resolved by first invoking `ninja -C out/Debug mojo/public/tools/bindings`

This indicates that the target ` mojo/public/tools/bindings` needs to be a dependency  of something that it is currently not a dependency of.

**Comment by MitchRudominer** [comment]
\cc @AlexandreZani

**Comment by viettrungluu-cr** [comment]
@MitchRudominer Is this issue obsolete? Can we close it?
