### ISSUE TITLE
New Mojom Parser: Test the parser using mojo/public/interfaces/bindings/tests

### ISSUE THREAD

**Issue by MitchRudominer** [domokit/mojo#549]
There are lots of good test cases in the mojom files in mojo/public/interfaces/bindings/tests.

I have already found two problems:

(1) A go panic:
```
panic: ref.resolvedDeclaredValue is neither a DelcaredConstant, an EnumValue, nor a BuiltInConstantValue.
```
```
goroutine 1 [running]:
mojom/mojom_parser/mojom.(*MojomDescriptor).resolveValueRef(0xc82005c0e0, 0xc820096100, 0x6)
	/home/rudominer/mojo/src/mojom/mojom_parser/mojom/mojom_descriptor.go:415 +0x4bd
mojom/mojom_parser/mojom.(*MojomDescriptor).resolveValueReferences(0xc82005c0e0, 0xc820015c20, 0x6, 0x6, 0x0, 0x0)
	/home/rudominer/mojo/src/mojom/mojom_parser/mojom/mojom_descriptor.go:358 +0x10f
mojom/mojom_parser/mojom.(*MojomDescriptor).Resolve(0xc82005c0e0, 0x0, 0x0)
	/home/rudominer/mojo/src/mojom/mojom_parser/mojom/mojom_descriptor.go:286 +0xc3
mojom/mojom_parser/parser.(*ParseDriver).ParseFiles(0xc8200a5ee8, 0xc82000a470, 0x1, 0x1, 0xc82005c0e0, 0x0, 0x0)
	/home/rudominer/mojo/src/mojom/mojom_parser/parser/parse_driver.go:145 +0xc05
main.main()
	/home/rudominer/mojo/src/mojom/mojom_parser/parser_main.go:89 +0x539

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/google/home/gauthamt/mojo/src/third_party/go/tool/linux_amd64/src/runtime/asm_amd64.s:1696 +0x1
Traceback (most recent call last):
  File "../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 36, in <module>
    sys.exit(main())
  File "../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 30, in main
    mojom_bindings_generator_v2.main(remaining_args)
  File "/home/rudominer/mojo/src/mojo/public/tools/bindings/mojom_bindings_generator_v2.py", line 119, in main
    serialized_file_graph = RunParser(args)
  File "/home/rudominer/mojo/src/mojo/public/tools/bindings/mojom_bindings_generator_v2.py", line 45, in RunParser
    return subprocess.check_output(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['../../mojom/mojom_parser/bin/linux64/mojom_parser', '-I', '../../,../../', '../../mojo/public/interfaces/bindings/tests/test_constants.mojom']' returned non-zero exit 
```
(2) A possibly erroneous parser error message:
```
Error while parsing ../../mojo/public/interfaces/bindings/tests/test_structs.mojom: 
Illegal assignment at line 86, column 14: Field f9 of type float may not be assigned the value 100 of type int8.
```
```
//mojo/public/interfaces/bindings/tests:test_interfaces__generator(//build/toolchain/linux:clang_x64)
FAILED: python ../../mojo/public/tools/bindings/mojom_bindings_generator.py ../../mojo/public/interfaces/bindings/tests/test_structs.mojom --use_bundled_pylibs -d ../../ -I ../../ -I ../../ -o /home/rudominer/mojo/src/out/Debug/gen --compiler-version=2 --python-bindings-dir /home/rudominer/mojo/src/out/Debug/python

Error while parsing ../../mojo/public/interfaces/bindings/tests/test_structs.mojom: 
Illegal assignment at line 86, column 14: Field f9 of type float may not be assigned the value 100 of type int8.

Traceback (most recent call last):
  File "../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 36, in <module>
    sys.exit(main())
  File "../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 30, in main
    mojom_bindings_generator_v2.main(remaining_args)
  File "/home/rudominer/mojo/src/mojo/public/tools/bindings/mojom_bindings_generator_v2.py", line 119, in main
    serialized_file_graph = RunParser(args)
  File "/home/rudominer/mojo/src/mojo/public/tools/bindings/mojom_bindings_generator_v2.py", line 45, in RunParser
    return subprocess.check_output(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['../../mojom/mojom_parser/bin/linux64/mojom_parser', '-I', '../../,../../', '../../mojo/public/interfaces/bindings/tests/test_structs.mojom']' returned non-zero exit status 1
```

**Comment by MitchRudominer** [comment]
blocks #547
