### ISSUE TITLE
dart mojom package should print a useful error on compilation failure

### ISSUE THREAD

**Issue by alhaad** [domokit/mojo#650]
When using the mojom dart package for generating dart bindings, if there is a compilation failure the error is something like:
```
Unhandled exception:
FileSystemException: Deletion failed, path = '/tmp/vbWzwF' (OS Error: No such file or directory, errno = 2)
#0      _Directory._delete.<anonymous closure> (dart:io/directory_impl.dart:183)
#1      _RootZone.runUnary (dart:async/zone.dart:1149)
#2      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:551)
#3      _Future._propagateToListeners (dart:async/future_impl.dart:637)
#4      _Future._completeWithValue (dart:async/future_impl.dart:424)
#5      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:479)
#6      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#7      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#8      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

```

It should print something more useful.

/cc @zanderso

**Comment by zanderso** [comment]
https://codereview.chromium.org/1680313002
