### ISSUE TITLE
Dart bindings: It's unclear which non-nullable field is being assigned to null

### ISSUE THREAD

**Issue by Hixie** [domokit/mojo#653]
The dart bindings encode a null pointer like this:
```dart
  void encodeNullPointer(int offset, bool nullable) {
    if (!nullable) {
      throw new MojoCodecError(
          "Trying to encode a null pointer for a non-nullable type");
    }
    _buffer.buffer.setUint64(_base + offset, 0, Endianness.LITTLE_ENDIAN);
  }
```
Notice how if it's not nullable, it throws. The stacks look something like:
```
#0      Encoder.encodeNullPointer (mojo/lib/src/codec.dart:256)
#1      SemanticsNode.encode (semantics.mojom.dart:106)
#2      Encoder.encodeStruct (mojo/lib/src/codec.dart:279)
#3      SemanticsNode.encode (semantics.mojom.dart:111)
#4      Encoder.encodeStruct (mojo/lib/src/codec.dart:279)
#5      SemanticsNode.encode (semantics.mojom.dart:111)
#6      Encoder.encodeStruct (mojo/lib/src/codec.dart:279)
#7      _SemanticsListenerUpdateSemanticsTreeParams.encode (semantics.mojom.dart:485)
#8      Struct.serializeWithHeader (mojo/lib/src/struct.dart:23)
#9      Proxy.sendMessage (mojo/lib/src/proxy.dart:86)
#10     _SemanticsListenerProxyCalls.updateSemanticsTree (semantics.mojom.dart:1020)
```

This doesn't give you any information about exactly _which_ field was null.

cc @zra.

**Comment by zanderso** [comment]
The source locations in semantics.mojom.dart from the stack trace probably have the information you'd like. I'll see if I can make the error message better here, though.

**Comment by Hixie** [comment]
Yeah, you can figure it out if you go debugging in the generated code. But I hope we can do better. :-)

**Comment by zanderso** [comment]
https://codereview.chromium.org/1668673002/
