### ISSUE TITLE
Mojo waterfall is currently broken

### ISSUE THREAD

**Issue by MitchRudominer** [domokit/mojo#715]
As of 17:16 this afternoon, after my commit of https://codereview.chromium.org/1798283002, the Mojo waterfall has been partially red. The Go system tests are failing on Mojo Linux and Mojo Linux (dbg) with

```
--- FAIL: TestEnumType (0.00s)
	validation_type_test.go:33: Descriptor did not contain BasicEnum
--- FAIL: TestStructType (0.00s)
	validation_type_test.go:110: Descriptor did not contain StructE
--- FAIL: TestUnionType (0.00s)
	validation_type_test.go:206: Descriptor did not contain UnionB
--- FAIL: TestStructWithImportType (0.00s)
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map

goroutine 429 [running]:
testing.tRunner.func1(0xc82054d950)
	/usr/local/google/home/gauthamt/mojo/src/third_party/go/tool/linux_amd64/src/testing/testing.go:449 +0x171
mojo/public/interfaces/bindings/tests/test_unions.initRuntimeTypeInfo()
	/b/build/slave/mojo/build/src/out/Debug/gen/go/src/mojo/public/interfaces/bindings/tests/test_unions/test_unions.mojom.go:65 +0x9d9
mojo/public/interfaces/bindings/tests/test_unions.getRuntimeTypeInfo(0x0, 0x0)
	/b/build/slave/mojo/build/src/out/Debug/gen/go/src/mojo/public/interfaces/bindings/tests/test_unions/test_unions.mojom.go:34 +0x2e
mojo/public/interfaces/bindings/tests/test_unions.GetAllMojomTypeDefinitions(0xc820304528)
	/b/build/slave/mojo/build/src/out/Debug/gen/go/src/mojo/public/interfaces/bindings/tests/test_unions/test_unions.mojom.go:71 +0x18
mojo/public/interfaces/bindings/tests/test_unions.IncludingStructMojomType(0x0, 0x0)
	/b/build/slave/mojo/build/src/out/Debug/gen/go/src/mojo/public/interfaces/bindings/tests/test_unions/test_unions.mojom.go:2336 +0x24
command-line-arguments.TestStructWithImportType(0xc82054d950)
	/b/build/slave/mojo/build/src/mojo/go/tests/validation_type_test.go:287 +0x135
testing.tRunner(0xc82054d950, 0xde3bd0)
```
I am unable to reproduce the problem locally and I am conjecturing that the issue is that some .mojom.go files need to be regenerated on the bots.

I am hoping that https://codereview.chromium.org/1804833002/ will fix the problem.

**Comment by MitchRudominer** [comment]
Looks good now.
