### ISSUE TITLE
dart example_tests.py is super-flaky/mostly fails

### ISSUE THREAD

**Issue by viettrungluu-cr** [domokit/mojo#723]
At c7fc1d1c06fab3dab3e1b111ee417688b841a7a0 (Linux Debug build), it mostly fails (see below), though occasionally succeeds.
```
vtl@ruxpin:~/projects/mojo/src$ python examples/dart/example_tests.py --build-dir out/Debug
00:00 +0: Hello, .mojo!
00:30 +0 -1: Hello, .mojo!
  TimeoutException after 0:00:30.000000: Test timed out after 30 seconds.
  dart:isolate  _RawReceivePortImpl._handleMessage
  
00:30 +0 -1: Hello, .dart!
00:32 +1 -1: Some tests failed.

Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:883)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
Traceback (most recent call last):
  File "examples/dart/example_tests.py", line 59, in <module>
    sys.exit(main(args.build_dir, package_root))
  File "examples/dart/example_tests.py", line 46, in main
    RunTests(tests, build_dir, package_root)
  File "examples/dart/example_tests.py", line 41, in RunTests
    '--mojo-shell', os.path.join(build_dir, 'mojo_shell'),])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/google/home/vtl/projects/mojo/src/third_party/dart-sdk/dart-sdk/bin/dart', '-p', '/usr/local/google/home/vtl/projects/mojo/src/out/Debug/gen/dart-pkg/packages', '--checked', '/usr/local/google/home/vtl/projects/mojo/src/examples/dart/hello_world/hello/test/hello_test.dart', '--mojo-shell', 'out/Debug/mojo_shell']' returned non-zero exit status 255
vtl@ruxpin:~/projects/mojo/src$ 
```

/cc @johnmccutchan @zanderso

**Comment by afandria** [comment]
Here are my observations:
* Run with multiprocess. The flake doesn't occur anymore.
  For just the hello test, it would be the difference between
  `dart -p $MOJO_DIR/src/out/Debug/gen/dart-pkg/packages --checked examples/dart/hello_world/hello/test/hello_test.dart --mojo-shell $MOJO_DIR/src/out/Debug/mojo_shell` and `dart -p $MOJO_DIR/src/out/Debug/gen/dart-pkg/packages --checked examples/dart/hello_world/hello/test/hello_test.dart --mojo-shell $MOJO_DIR/src/out/Debug/mojo_shell -- --enable-multiprocess`

* Add printouts in the `Hello, .dart!` test. Even if the test times out, all the printouts occur anyway.

  (zzz at start, A prints out the args, B prints result.stdout, C and D wrap the `server.close()` call)

  On fail...
  ```
00:00 +0: Hello, .mojo!
00:30 +0 -1: Hello, .mojo!
  TimeoutException after 0:00:30.000000: Test timed out after 30 seconds.
  dart:isolate  _RawReceivePortImpl._handleMessage
  
00:30 +0 -1: Hello, .dart!
zzz
A [http://127.0.0.1:35290/hello/lib/main.dart]
B Observatory listening on http://127.0.0.1:56092
http://127.0.0.1:35290/hello/lib/main.dart Hello
Connecting to http://127.0.0.1:35290/world/lib/main.dart
http://127.0.0.1:35290/world/lib/main.dart World

C
D
00:30 +1 -1: Some tests failed.

Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

  On success
  ```
00:00 +0: Hello, .mojo!
00:00 +1: Hello, .dart!
zzz
A [--enable-multiprocess, http://127.0.0.1:39066/hello/lib/main.dart]
B Observatory listening on http://127.0.0.1:53697
http://127.0.0.1:39066/hello/lib/main.dart Hello
Connecting to http://127.0.0.1:39066/world/lib/main.dart
http://127.0.0.1:39066/world/lib/main.dart World

C
D
00:01 +2: All tests passed!
```

Overall, I'm not really sure what this means. Maybe the test succeeds but something doesn't quit?

If that is the case, it doesn't seem related to #729.

**Comment by zanderso** [comment]
@afandria Looking at the failure trace, the first test (Hello, .mojo!) times out, and the second test (Hello, .dart!) succeeds, generating your debug prints. Judging from the success trace, there aren't any debug prints for the first test. I will take a look.

**Comment by zanderso** [comment]
https://codereview.chromium.org/1831263003/

I suspect the real fix is to remove this hack: https://github.com/dart-lang/sdk/blob/master/runtime/vm/service_isolate.cc#L467

I'll discuss with @johnmccutchan offline.
