### ISSUE TITLE
Cannot make dart:io socket connections from Mojo Dart content handler

### ISSUE THREAD

**Issue by schwa423** [domokit/mojo#781]
I tried many different ways.  All failed, some differently than others.  

Here is the code I used.  All of these run fine from the command line in the regular Dart VM, and all fail in the Dart content handler (some fail differently than others, observations follow...)

    void makeRequest(Socket socket) {
      socket.listen((data) {
        print(new String.fromCharCodes(data).trim());
      },
      onDone: () {
        print("Done");
        socket.destroy();
      });
      //Send the request
      String indexRequest = 'GET / HTTP/1.1\nConnection: close\n\n';
      socket.write(indexRequest);
    }

    // 1
    Future<Null> talkToGoogleHostname() async {
      makeRequest(await Socket.connect('www.google.com', 80));
    }

    // 2
    Future<Null> talkToGoogleIpv6() async {
      var address	= (await InternetAddress.lookup('www.google.com'))[0];
      makeRequest(await Socket.connect(address, 80));
    }

    // 3
    Future<Null> talkToGoogleIpv4() async {
      var address	= (await InternetAddress.lookup('www.google.com'))[1];
      makeRequest(await Socket.connect(address, 80));
    }

    // 4
    Future<Null> talkToGoogleSslHostname() async {
      makeRequest(await SecureSocket.connect('www.google.com', 443));
    }

    // 5
    Future<Null> talkToGoogleSslIpv6() async {
      var address	= (await InternetAddress.lookup('www.google.com'))[0];
      makeRequest(await SecureSocket.connect(address, 443));
    }

    // 6
    Future<Null> talkToGoogleSslIpv4() async {
      var address	= (await InternetAddress.lookup('www.google.com'))[1];
      makeRequest(await SecureSocket.connect(address, 443));
    }

**Comment by schwa423** [comment]
Snippets #1 and #4 fail like this.  When I look at the implementation of _MojoRawSocket._connect(), it seems like maybe the problem is that I'm passing the hostname as a String, instead of passing an InternetAddress.

[0520/162654:ERROR:dart_error.cc(19)] Unhandled exception:
OS Error: net::ERR_CONNECTION_REFUSED, errno = -102
#0      _NetworkService._throwOnError (dart:io-patch/io/mojo_patch.dart:300:5)
#1      _MojoRawSocket._connect.<_connect_async_body> (dart:io-patch/io/socket_patch.dart:186:23)
#2      _RootZone.runUnary (dart:async/zone.dart:1204)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#4      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:628)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:658)
#6      _Future._completeWithValue (dart:async/future_impl.dart:468)
#7      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:519)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#10     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

**Comment by schwa423** [comment]
Snippets #2 and #5 fail with the same call-stack but a different error:
OS Error: net::ERR_ADDRESS_UNREACHABLE, errno = -109

Snippets #3 and #6 also fail with the same call-stack, but with yet another error:
OS Error: net::ERR_INVALID_ARGUMENT, errno = -4

**Comment by zanderso** [comment]
@johnmccutchan 

There is no support for dart:io secure sockets in the Mojo content handler, so 4-6 are expected to fail. It may also be helpful in debugging this to inspect the addresses returned by InternetAddress.lookup
